[options]
addons_path = /app/addons,/app/odoo/addons
admin_passwd = admin123

db_host = postgres.railway.internal
db_port = 5432
db_user = postgres
db_password = XbbWHIYnurwPPVLnXWGCoJyFlCozeIuv
db_name = railway

log_level = info
